#!/bin/bash

# WINE env
export WINEPREFIX=${WINEPREFIX:-"$HOME/.wine-appimage"}
export WINEDEBUG=${WINEDEBUG:-"fixme-all"}

# DXVK env
export DXVK_HUD=${DXVK_HUD:-"0"}
export DXVK_LOG_LEVEL=${DXVK_LOG_LEVEL:-"none"}
export DXVK_STATE_CACHE=${DXVK_STATE_CACHE:-"0"}
export DXVK_CONFIG_FILE=${DXVK_CONFIG_FILE:-"$progHome/dxvk.conf"}

# check gpu vendor
VENDOR=$(glxinfo -B | grep "OpenGL vendor")

SLASH="/"
USR_FOLDER="${SLASH}usr"
if [[ $VENDOR == *"Intel"* ]]; then
  export VK_ICD_FILENAMES="$USR_FOLDER/share/vulkan/icd.d/intel_icd.i686.json:$USR_FOLDER/share/vulkan/icd.d/intel_icd.x86_64.json"
elif [[ $VENDOR == *"NVIDIA"* ]]; then
  export VK_ICD_FILENAMES="$USR_FOLDER/share/vulkan/icd.d/nvidia_icd.json"
elif [[ $VENDOR == *"Radeon"* ]]; then
  export VK_ICD_FILENAMES="$USR_FOLDER/share/vulkan/icd.d/radeon_icd.i686.json:$USR_FOLDER/share/vulkan/icd.d/radeon_icd.x86_64.json"
fi

# Load winecfg if no arguments given
APPLICATION=""
if [ -z "$*" ] ; then
  APPLICATION="winecfg"
fi

# Allow the AppImage to be symlinked to e.g., /usr/bin/wineserver
if [ -n "$APPIMAGE" ] ; then
  BINARY_NAME=$(basename "$ARGV0")
else
  BINARY_NAME=$(basename "$0")
fi

if [ -n "$1" ] && [ -e "$APPDIR/bin/$1" ] ; then
  MAIN="$APPDIR/bin/$1" ; shift
elif [ -n "$1" ] && [ -e "$APPDIR/usr/bin/$1" ] ; then
  MAIN="$APPDIR/usr/bin/$1" ; shift
elif [ -n "$1" ] && [ -e "$1" ] ; then
  MAIN="$1" ; shift
elif [ -e "$APPDIR/bin/$BINARY_NAME" ] ; then
  MAIN="$APPDIR/bin/$BINARY_NAME"
elif [ -e "$APPDIR/usr/bin/$BINARY_NAME" ] ; then
  MAIN="$APPDIR/usr/bin/$BINARY_NAME"
elif [ -e "$APPDIR/usr/bin/wine64" ] ; then
  MAIN="$APPDIR/usr/bin/wine64"
elif [ -e "$APPDIR/usr/bin/wine" ] ; then
  MAIN="$APPDIR/usr/bin/wine"
fi

if [ -n "$WINE_WORKDIR" ] ; then
  cd $WINE_WORKDIR
fi

if [ -z "$APPLICATION" ] ; then
"$MAIN" "$@" | cat
else
"$MAIN" "$APPLICATION" | cat
fi
